### ISSUE TITLE
App crash on startup 

### ISSUE THREAD

**Issue by Afur** [CrossGeeks/FirebasePushNotificationPlugin#2]
I've done everything like in your tutorial. But when I try to launch android app it's crash at startup and returns  Unhandled Exception. When I mark `FirebasePushNotificationManager.Initialize(this,true);` and ` FirebasePushNotificationManager.ProcessIntent(Intent);` as a comment app works as normal without any issue.

**Comment by Afur** [comment]
Update:

After Rebuild All everything works fine. But then if I restart my project and I try to debug app exception appears again.

**Comment by rdelrosario** [comment]
What's the exception?

**Comment by rdelrosario** [comment]
Can you put the stack trace here please

**Comment by rdelrosario** [comment]
I guess the issue might be:

The following describe issue might arise when using Firebase Cloud Messaging with Xamarin.Android.

FirebaseApp is not Initialized

In some cases, you may see this error message:

Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process 
Make sure to call FirebaseApp.initializeApp(Context) first.

This is a known problem that you can work around by cleaning the solution and rebuilding the project (Build > Clean Solution, Build > Rebuild Solution). For more information, see this forum discussion:

https://forums.xamarin.com/discussion/96263/default-firebaseapp-is-not-initialized-in-this-process

There's a good fix that avoids you having to do clean -> rebuild each time here:

https://bugzilla.xamarin.com/show_bug.cgi?id=56108

**Comment by Afur** [comment]
Thank you very much!

**Solution:**

This code added to .csproj 

`<Target Name="RemoveGoogleServicesJsonStampFiles" BeforeTargets="BeforeBuild">
    <Delete Files="$(IntermediateOutputPath)\ProcessGoogleServicesJson.stamp" />
  </Target>`

**Comment by ashishbpatil1** [comment]
I am facing same issue here. I've done everything like in your tutorial. And it works well in debug mode But when I try to launch android app after removing cable it's crash at startup. It says 

> Unfortunately, MyProject.Android has stopped.

Logged error:

```
Error: Unhandled Exception
System.Exception: CurrentDomainOnUnhandledException ---> Java.Lang.RuntimeException: java.lang.reflect.InvocationTargetException ---> Java.Lang.Reflect.InvocationTargetException: Exception of type 'Java.Lang.Reflect.InvocationTargetException' was thrown. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Plugin.FirebasePushNotification.FirebasePushNotificationManager.ProcessIntent (Android.Content.Intent intent, System.Boolean enableDelayedResponse) [0x00081] in <602a838c005a49b48f7f29fdbdce3ecf>:0 
  at SmartSensor.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00071] in <63ac03cfe1334bc18afd48993712fc08>:0 
  at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <8b5e0f4c6f594871ab0afcbcb2317289>:0 
  at (wrapper dynamic-method) System.Object:71482e7c-b6d3-4adb-83a4-02bdc3521fef (intptr,intptr,intptr)
```

I've also added these lines in android csproj file.

`<Target Name="RemoveGoogleServicesJsonStampFiles" BeforeTargets="BeforeBuild"> <Delete Files="$(IntermediateOutputPath)\ProcessGoogleServicesJson.stamp" /> </Target>`

Can u please tell me what is wrong. 
Thanks in advance.

**Comment by BhaurajBiradar001** [comment]
Still I am receiving below error, any solution??

FirebasePushNotificationManager.Initialize(this, true);  // Here app crashes

Default FirebaseApp is not initialized in this process com.firebase.sampleapp. Make sure to call FirebaseApp.initializeApp(Context) first.

// Stacktrace

{Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.firebase.sampleapp. Make sure to call FirebaseApp.initializeApp(Context) first.
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <00c315a988634383b446eff646084784>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <00c315a988634383b446eff646084784>:0 
  at Firebase.Messaging.FirebaseMessaging.get_Instance () [0x00000] in C:\a\_work\2\s\generated\com.google.firebase.firebase-messaging\obj\Release\monoandroid12.0\generated\src\Firebase.Messaging.FirebaseMessaging.cs:106 
  at Plugin.FirebasePushNotification.FirebasePushNotificationManager.Initialize (Android.Content.Context context, System.Boolean resetToken, System.Boolean createDefaultNotificationChannel, System.Boolean autoRegistration) [0x0002a] in /Users/runner/work/1/s/Plugin.FirebasePushNotification/FirebasePushNotificationManager.android.cs:123 
  at TotalConnect.Droid.MainApplication.OnCreate () [0x00032] in C:\Dev_Git\tc20e\TotalConnect\TotalConnect.Android\NotifApp.cs:37 
  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.honeywell.totalconnect. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
	at com.google.firebase.messaging.FirebaseMessaging.getInstance(com.google.firebase:firebase-messaging@@22.0.0:1)
	at crc6484fc9659366f968b.MainApplication.n_onCreate(Native Method)
	at crc6484fc9659366f968b.MainApplication.onCreate(MainApplication.java:25)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7598)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2397)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
}
