### ISSUE TITLE
Deployment failed on Android 6.0.1

### ISSUE THREAD

**Issue by RiccardoScarpa** [CrossGeeks/FirebasePushNotificationPlugin#204]
When I try to deploy an app with FirebasePushNotificationPlugin to android 6.0.1 this error occur

Severity	Code	Description	Project	File	Line	Suppression State
Error		ADB0000:  Deployment failed
Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]
   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in E:\A\_work\293\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 341
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t) in E:\A\_work\293\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 753
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()		 	0	

Severity	Code	Description	Project	File	Line	Suppression State
Error		ADB0010: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]
   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in E:\A\_work\293\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 341
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t) in E:\A\_work\293\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 753
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()		 	0	

If I try to deploy to Android 8.1.0 all works fine.

## Bug Information

Version Number of Plugin: 2.3.5
Device Tested On: Panasonic FZ-N1
Device Tested On: Huawei P20
Simulator Tested On:
Version of VS: 15.9.4
Version of Xamarin: 4.12.3.77
Versions of other things you are using:

**Comment by alexey-gorshkov** [comment]
Open terminal, and type adb shell to access the emulator shell.

    $ adb shell settings put global verifier_verify_adb_installs 0
