### ISSUE TITLE
add support to W/FirebaseMessaging: Error while parsing timestamp in GCM event

### ISSUE THREAD

**Issue by alextorres50** [CrossGeeks/FirebasePushNotificationPlugin#208]
## Bug Information

Version Number of Plugin: 2.3.5
Device Tested On: Some Devices Xiaomi, Samsung and Huawei
Simulator Tested On: -
Version of VS: Visual Studio 2017 for Mac version 7.7
Version of Xamarin: 3.4.1.0.697729
Versions of other things you are using:
Xamarin.Firebase.Messaging 60.11421.1
### Steps to reproduce the Behavior
The notification when the app is on foreground , the app crash for this issue on firebase messaging 
W/FirebaseMessaging: Error while parsing timestamp in GCM event
    java.lang.NumberFormatException: s == null
        at java.lang.Integer.parseInt(Integer.java:570)
        at java.lang.Integer.valueOf(Integer.java:794)
        at com.google.firebase.messaging.zzd.zzb(Unknown Source:62)
        at com.google.firebase.messaging.zzd.zzi(Unknown Source:2)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source:365)
        at com.google.firebase.iid.zzg.run(Unknown Source:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
 
this bug fixed with the new version of Xamarin.Messaging 70.1710.0-preview2 but, for now this version is a Pre-Release and the plugin is not compatible with that versions 
### Expected Behavior
- the plugin add support to pre releases version of Xamarin.Messaging, this issue is critical
### Actual Behavior
- the app crash when the app is on foreground mode and send a notification to device

**Comment by rdelrosario** [comment]
Fixed on latest release
