### ISSUE TITLE
Notifications do not arrive when the app is closed

### ISSUE THREAD

**Issue by dertin** [CrossGeeks/FirebasePushNotificationPlugin#250]
## Bug Information

Version Number of Plugin: 2.3.6
Versions of other things you are using:
Xamarin.Firebase.Messaging 60.11421.1

### Steps to reproduce the Behavior

```
CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
{
   // only the first notification arrives then an error exception is already generated.
}

```
Error Exception:
W/FirebaseMessaging: Error while parsing timestamp in GCM event:

#162 
#206 
#208 

```
I/FirebaseInitProvider(12117): FirebaseApp initialization successful
I/art     (  948): Explicit concurrent mark sweep GC freed 49576(2MB) AllocSpace objects, 13(2MB) LOS objects, 30% free, 36MB/52MB, paused 2.011ms total 182.100ms
W/FirebaseMessaging(12117): Error while parsing timestamp in GCM event
W/FirebaseMessaging(12117): java.lang.NumberFormatException: Invalid int: "null"
W/FirebaseMessaging(12117): 	at java.lang.Integer.invalidInt(Integer.java:138)
W/FirebaseMessaging(12117): 	at java.lang.Integer.parseInt(Integer.java:358)
W/FirebaseMessaging(12117): 	at java.lang.Integer.parseInt(Integer.java:334)
W/FirebaseMessaging(12117): 	at java.lang.Integer.valueOf(Integer.java:525)
W/FirebaseMessaging(12117): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source)
W/FirebaseMessaging(12117): 	at com.google.firebase.messaging.zzd.zzg(Unknown Source)
W/FirebaseMessaging(12117): 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
W/FirebaseMessaging(12117): 	at md57ed5f67be73a82ec2979b0c5477cb49b.MyFirebaseMessagingService.n_handleIntent(Native Method)
W/FirebaseMessaging(12117): 	at md57ed5f67be73a82ec2979b0c5477cb49b.MyFirebaseMessagingService.handleIntent(MyFirebaseMessagingService.java:30)
W/FirebaseMessaging(12117): 	at com.google.firebase.iid.zzc.run(Unknown Source)
W/FirebaseMessaging(12117): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/FirebaseMessaging(12117): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/FirebaseMessaging(12117): 	at java.lang.Thread.run(Thread.java:818)
I/FA      (12117): Tag Manager is not found and thus will not be used
```
It is critical to support the new version. Xamarin.Firebase.Messaging 71.1740.0

**Comment by mimunoz** [comment]
Hi, have you check this #244 ?

**Comment by rdelrosario** [comment]
Fixed on latest release
