### ISSUE TITLE
Not able to compile and run project

### ISSUE THREAD

**Issue by SagarPanwala** [CrossGeeks/FirebasePushNotificationPlugin#314]
## 🐛 Bug Report

After updating all packages , I'm not able to build the project.
Error I'm getting is
Error XALNK7028: System.IO.FileNotFoundException: Could not load assembly 'Plugin.FirebasePushNotification.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Plugin.FirebasePushNotification.Abstractions.dll'
  at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x0009a] in /Users/runner/runners/2.165.0/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:241 
  at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) [0x00000] in /Users/runner/runners/2.165.0/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:191 
  at Mono.Cecil.MetadataResolver.Resolve (Mono.Cecil.TypeReference type) [0x0003a] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/external/cecil/Mono.Cecil/MetadataResolver.cs:110 
  at Mono.Cecil.ModuleDefinition.Resolve (Mono.Cecil.TypeReference type) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:762 
  at Mono.Cecil.TypeReference.Resolve () [0x0000f] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/external/cecil/Mono.Cecil/TypeReference.cs:280 
  at Mono.Linker.TypeReferenceExtensions+<GetMethods>d__4.MoveNext () [0x00027] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Steps.TypeMapStep.TryMatchMethod (Mono.Cecil.TypeReference type, Mono.Cecil.MethodReference method) [0x00027] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Steps.TypeMapStep+<GetBaseMethodsInInterfaceHierarchy>d__16.MoveNext () [0x0005b] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Steps.TypeMapStep.MapVirtualInterfaceMethod (Mono.Cecil.MethodDefinition method) [0x0001e] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Steps.TypeMapStep.MapVirtualMethod (Mono.Cecil.MethodDefinition method) [0x00007] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods (Mono.Cecil.TypeDefinition type) [0x00027] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Steps.TypeMapStep.MapType (Mono.Cecil.TypeDefinition type) [0x00000] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Steps.TypeMapStep.ProcessAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x0001b] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Steps.BaseStep.Process (Mono.Linker.LinkContext context) [0x00025] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Pipeline.ProcessStep (Mono.Linker.LinkContext context, Mono.Linker.Steps.IStep step) [0x0000d] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0000f] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at MonoDroid.Tuner.Linker.Run (Mono.Linker.Pipeline pipeline, Mono.Linker.LinkContext context) [0x00000] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at MonoDroid.Tuner.Linker.Process (MonoDroid.Tuner.LinkerOptions options, Mono.Linker.ILogger logger, Mono.Linker.LinkContext& context) [0x00071] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x001dd] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Xamarin.Android.Tasks.LinkAssemblies.RunTask () [0x0001b] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0 
  at Xamarin.Android.Tasks.AndroidTask.Execute () [0x00000] in <e29c048b3b5443a3a8a19c4ed24d3a3a>:0  (XALNK7028)

### Expected behavior
- App should compile and work with push notification

### Reproduction steps
- Create new xamarin forms project, Target Android 10, add AndroidX.Migration package
- Add Plugin.FirebasePushNotification Package.

### Configuration
=== Visual Studio Community 2019 for Mac ===
Version 8.5.2 (build 13)

=== Mono Framework MDK ===
Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

=== NuGet ===
Version: 5.4.0.6315

=== Xamarin.Android ===
Version: 10.2.0.100 (Visual Studio Community)
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 29.0.2

Xamarin Forms : 4.5.0.657
Plugin.FirebasePushNotification : 3.1.6

**Platform:** 
- [:robot:] Android
- [:monkey:] Xamarin.Forms

**Comment by SagarPanwala** [comment]
Just an update, If I use 3.2.9-beta version of the library, project compiles, but it is crashing on launch with the following crashlog.




[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] java.lang.RuntimeException: Unable to instantiate receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.InstantiationException: java.lang.Class<com.google.firebase.iid.FirebaseInstanceIdReceiver> cannot be instantiated
[AndroidRuntime] 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3262)
[AndroidRuntime] 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1713)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:164)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6626)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
[AndroidRuntime] Caused by: java.lang.InstantiationException: java.lang.Class<com.google.firebase.iid.FirebaseInstanceIdReceiver> cannot be instantiated
[AndroidRuntime] 	at java.lang.Class.newInstance(Native Method)
[AndroidRuntime] 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3257)
[AndroidRuntime] 	... 8 more
[UncaughtException] 
[UncaughtException] java.lang.RuntimeException: Unable to instantiate receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.InstantiationException: java.lang.Class<com.google.firebase.iid.FirebaseInstanceIdReceiver> cannot be instantiated
[UncaughtException] 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3262)
[UncaughtException] 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
[UncaughtException] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1713)
[UncaughtException] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[UncaughtException] 	at android.os.Looper.loop(Looper.java:164)
[UncaughtException] 	at android.app.ActivityThread.main(ActivityThread.java:6626)
[UncaughtException] 	at java.lang.reflect.Method.invoke(Native Method)
[UncaughtException] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[UncaughtException] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
[UncaughtException] Caused by: java.lang.InstantiationException: java.lang.Class<com.google.firebase.iid.FirebaseInstanceIdReceiver> cannot be instantiated
[UncaughtException] 	at java.lang.Class.newInstance(Native Method)
[UncaughtException] 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3257)
[UncaughtException] 	... 8 more
