### ISSUE TITLE
App crashes when recieving a message

### ISSUE THREAD

**Issue by KrizCologne** [CrossGeeks/FirebasePushNotificationPlugin#317]
## 🐛 Bug Report

When I sent notifications to my apps in store, all apps crashes with following stacktrace:

```
Fatal Exception: java.lang.NoSuchFieldError: No static field zzaqu of type [Ljava/lang/String; in class Lcom/google/android/gms/measurement/AppMeasurement$UserProperty; or its superclasses (declaration of 'com.google.android.gms.measurement.AppMeasurement$UserProperty' appears in /data/app/com.modev.plutester-wwv-GsbRKa5K4IyDMS_noQ==/base.apk)
       at com.google.firebase.analytics.connector.internal.zzc.<clinit>(:154)
       at com.google.firebase.analytics.connector.internal.zzc.zzft(:1)
       at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.logEvent(:30)
       at com.google.firebase.messaging.MessagingAnalytics.zza(:72)
       at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(:2)
       at com.google.firebase.messaging.FirebaseMessagingService.zzd(:50)
       at com.google.firebase.iid.zzc.run(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(:6)
       at java.lang.Thread.run(Thread.java:764)
```

Same problem when try in debug mode with following stacktrace:

```
05-08 05:34:12.553 E/AndroidRuntime( 9497): FATAL EXCEPTION: Firebase-PNFirebaseMessagingService
05-08 05:34:12.553 E/AndroidRuntime( 9497): Process: com.modev.plutester, PID: 9497
05-08 05:34:12.553 E/AndroidRuntime( 9497): java.lang.NoSuchFieldError: No static field zzaqu of type [Ljava/lang/String; in class Lcom/google/android/gms/measurement/AppMeasurement$UserProperty; or its superclasses (declaration of 'com.google.android.gms.measurement.AppMeasurement$UserProperty' appears in /data/app/com.modev.plutester-8Ptu5dhHeoqWT5C-Y90HQA==/base.apk)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at com.google.firebase.analytics.connector.internal.zzc.<clinit>(Unknown Source:154)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at com.google.firebase.analytics.connector.internal.zzc.zzft(Unknown Source:1)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.logEvent(Unknown Source:30)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at com.google.firebase.messaging.MessagingAnalytics.zza(Unknown Source:72)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at com.google.firebase.messaging.MessagingAnalytics.logNotificationReceived(Unknown Source:2)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:50)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at com.google.firebase.iid.zzc.run(Unknown Source:2)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
05-08 05:34:12.553 E/AndroidRuntime( 9497): 	at java.lang.Thread.run(Thread.java:764)
05-08 05:34:12.810 D/libc    ( 9497): [NET] android_getaddrinfo_proxy get netid:0
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Mono.Debugging.VisualStudio.ExceptionsAdapter.OnUnhandledException(Object sender, TargetEventArgs args) in E:\A\_work\3268\s\src\Debugging.VisualStudio.Vsix\Integration\ExceptionsAdapter.cs:Zeile 83.
   bei Mono.Debugging.Client.DebuggerSession.OnTargetEvent(TargetEventArgs args) in E:\A\_work\3268\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Client\DebuggerSession.cs:Zeile 1204.
   bei Mono.Debugging.Soft.SoftDebuggerSession.HandleBreakEventSet(Event[] es, Boolean dequeuing) in E:\A\_work\3268\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:Zeile 2057.
   bei Mono.Debugging.Soft.SoftDebuggerSession.HandleEventSet(EventSet es) in E:\A\_work\3268\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:Zeile 1740.
   bei Mono.Debugging.Soft.SoftDebuggerSession.EventHandler() in E:\A\_work\3268\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerSession.cs:Zeile 1640.
```

### Expected behavior
Should not crash

### Configuration
Latest Xamarin.Forms Version
Latest Plugin Version

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by ia5634** [comment]
+1
