### ISSUE TITLE
Android with AndroidX SERVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by moreirawebmaster** [CrossGeeks/FirebasePushNotificationPlugin#318]
## 🐛 Bug Report

Java.IO.IOException: SERVICE_NOT_AVAILABLE
  at Plugin.FirebasePushNotification.FirebasePushNotificationManager.GetTokenAsync () [0x00092] in <4a9f9b43b74b4a9fb9bd18b7778c2743>:0 
  --- End of managed Java.IO.IOException stack trace ---
java.io.IOException: SERVICE_NOT_AVAILABLE
	at com.google.firebase.iid.zzr.zza(Unknown Source:56)
	at com.google.firebase.iid.zzr.zza(Unknown Source:80)
	at com.google.firebase.iid.zzu.then(Unknown Source:4)
	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

### Configuration

**Version:** 3.1.6

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by moreirawebmaster** [comment]
look GetTokenAsync race condition #316 .
