### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by NPadrutt** [CrossGeeks/FirebasePushNotificationPlugin#35]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.0.7 and 2.0.1 Alpha
Device Tested On: HTC 10
Simulator Tested On: 
Version of VS: 2017 15.3.5
Version of Xamarin: 4.7.9.45
Versions of other things you are using: 7.4.5.1

### Steps to reproduce the Behavior
I start the application

### Expected Behavior
The app starts and I receive a new token.

### Actual Behavior
The app crashes during launch with the following exception:

```
10-05 21:13:57.590 E/mono-rt (14563): [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.postkca.friendsappdate. Make sure to call FirebaseApp.initializeApp(Context) first.
10-05 21:13:57.590 E/mono-rt (14563):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-05 21:13:57.590 E/mono-rt (14563):   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method) [0x00068] in <e499a5498b1b48379b88fe5ed629079f>:0 
10-05 21:13:57.590 E/mono-rt (14563):   at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod) [0x0000e] in <2e14bb2dd93a405e81838369ed72695b>:0 
10-05 21:13:57.590 E/mono-rt (14563):   at Firebase.Iid.FirebaseInstanceId.get_Instance () [0x00032] in <09a4f89addb34f02af055f39e6c540b7>:0 
10-05 21:13:57.590 E/mono-rt (14563):   at Plugin.FirebasePushNotification.FirebasePushNotificationManager+<>c__DisplayClass32_0.<Initialize>b__0 (System.Object state) [0x00177] in C:\Plugins\FirebasePushNotification\src\Plugin.FirebasePushNotification.Android\FirebasePushNotificationManager.cs:134 
10-05 21:13:57.590 E/mono-rt (14563):   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-05 21:13:57.590 E/mono-rt (14563):   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-05 21:13:57.590 E/mono-rt (14563):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-05 21:13:57.590 E/mono-rt (14563):   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-05 21:13:57.590 E/mono-rt (14563):   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-05 21:13:57.590 E/mono-rt (14563):   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-05 21:13:57.590 E/mono-rt (14563):   --- End of managed Java.Lang.IllegalStateException stack trace ---
10-05 21:13:57.590 E/mono-rt (14563): java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.postkca.friendsappdate. Make sure to call FirebaseApp.initializeApp(Context) first.
10-05 21:13:57.590 E/mono-rt (14563): 	at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
10-05 21:13:57.590 E/mono-rt (14563): 	at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
10-05 21:13:57.590 E/mono-rt (14563): 

```

### Code snippet
My Initialization is:
```

            FirebasePushNotificationManager.Initialize(this, true);
            FirebasePushNotificationManager.ProcessIntent(Intent);
```
I put both in the SplashActivity.  I also tried to put the first statement into my BaseApplication or my MainActivity without success.

**Comment by rdelrosario** [comment]
Make sure to call FirebaseApp.initializeApp(Context) first and the google-services.json has the GoogleServicesJson build action. If you have that set, then clean and build again, this is a known issue when using Firebase Component. More info and fix here: https://bugzilla.xamarin.com/show_bug.cgi?id=56108.

**Comment by NPadrutt** [comment]
A interesting clean and rebuild did it. Although I had google-services.json added a long time ago. But it seems the issue was, that I already had the two services declared in my project. When I removed them without clean and rebuild the issue appeared.

Thanks for your very fast support! :)
