### ISSUE TITLE
iOS app crashes at FirebasePushNotificationManager.Initialize

### ISSUE THREAD

**Issue by gordonsaxby** [CrossGeeks/FirebasePushNotificationPlugin#388]
## 🐛 Bug Report

App crashes at FirebasePushNotificationManager.Initialize with error:

{System.NullReferenceException: Object reference not set to an instance of an object.
  at Plugin.FirebasePushNotification.FirebasePushNotificationManager.Initialize (Foundation.NSDictionary options, System.Boolean autoRegistration) [0x00029] in /Users/runner/runners/2.169.1/work/1/s/Plugin.FirebasePushNotification/FirebasePushNotificationManager.ios.cs:141 
  at MyApp.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00014] in ....\MyApp\MyApp.iOS\AppDelegate.cs:34 }

### Expected behavior
Not to crash

### Reproduction steps
Create basic Xamarin Forms project with Visual Studio 2019. Add this Nuget package, add                 FirebasePushNotificationManager.Initialize(options, true); to AppDelegate.cs. Run on iPhone iOS v14.5

### Configuration

**Version:** 

3.3.10

**Platform:** 
- [x ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by jtorvald** [comment]
@gordonsaxby I'm running the same version without problems.
Did you add it after Xamarin.Forms.Forms.Init(); ?

**Comment by gordonsaxby** [comment]
I have followed the video here https://www.youtube.com/watch?v=GNBuaAB8nR8& and also the Android version and added all code, done all setup as per the videos.

The Android App runs fine and can receive notifications from Firebase. The iOS version compiles / installs, starts up and shows the default splash screen for 17 seconds and then the app stops (actually minimises) and debugging stops. No breakpoints within the iOS or shared projects are reached.

**Comment by jtorvald** [comment]
In your Main.cs replace this;
`UIApplication.Main(args, null, nameof(AppDelegate));`
with:
```
try
{
    UIApplication.Main(args, null, nameof(AppDelegate));
}
catch (Exception e)
{
    try
    {

        Debug.WriteLine(e.Message);
        Debug.WriteLine(e.StackTrace);
        Debug.WriteLine(e.Source);
        Debug.WriteLine(e.InnerException?.StackTrace);
        Debug.WriteLine(e.InnerException?.Source);

        //var data = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
        //var filename = Path.Combine(data, String.Format("crash.txt"));
        //File.WriteAllText(filename, e.Message + "\n-----\n" + e.StackTrace ?? "" + "\n-----\n" + e.Source ?? "" + "\n-----\n");
    }
    catch (DirectoryNotFoundException)
    {
    }
}

```
and see if that exception gives you a better clue of what is going on.

**Comment by gordonsaxby** [comment]
It doesn't reach that point. I added a breakpoint to the first WriteLine and it didn't hit it.

**Comment by jtorvald** [comment]
@gordonsaxby if you don't mind sharing your code (under NDA), I could have a quick look on my Macbook. I see that this issue is reported here a couple of times. I don't have it so I think I will be able to figure it out. I will send you a tweet so you know how to contact me.

**Comment by gordonsaxby** [comment]
I now have a physical Mac (MacBook Pro 2018) and the app works fine when run in debug mode from it (using Visual Studio 2019 for Mac). So, I can at least continue development, I just have to do testing of the iOS app from the MacBook.

Not really a solution, but at least shows the plugin does work. And that there is some sort of issue with using it via Windows.

**Comment by ThePharaon** [comment]
i have same issue on iPhone 7 iOS **v14.6** and package version **3.3.10**

**Comment by proximus323** [comment]
I have the same issue, can some one fix this ?

**Comment by Paulpetta668** [comment]
I had the same issue.

It was that it couldn't find the GoogleService-info.plist, I resolved it by set the buil option of the file:
![image](https://user-images.githubusercontent.com/48731892/125612516-61546f53-921a-44e8-8f4c-8afdd2a3e13d.png)

**Comment by proximus323** [comment]
Paulpetta668 you work on Windows or MacOS ?

**Comment by Paulpetta668** [comment]
> Paulpetta668 you work on Windows or macOS?

I work on Windows

**Comment by projectdownton** [comment]
No, a physical iPhone

**Comment by proximus323** [comment]
For now it only works from Mac.

**Comment by rkotulan** [comment]
We have the same issue, any idea how to fix this?

**Comment by proximus323** [comment]
Install VS on Mac, and create release there, on Windows not working :(

**Comment by rkotulan** [comment]
We are building on Azure Pipelines with Image: macOS-10.15 with the same result.

**Comment by rkotulan** [comment]
We fixed our issue adding InvokeOnMainThread 
```c#
CrossFirebasePushNotification.Current.OnNotificationError += (source, args) =>
                {
                    InvokeOnMainThread(
                        () => new UIAlertView(
                            "Error registering push notifications",
                            args.Message,
                            null as IUIAlertViewDelegate,
                            "OK",
                            null).Show());
                };
```

**Comment by nmano2188** [comment]
Facing same problem. Any workaround?

**Comment by omarsolarte** [comment]
face the same problem, help

**Comment by omatrot** [comment]
Same issue with an iPhone 13 connected to a Mac M1.

**Comment by robertev-alchemy** [comment]
Facing the same problem, and if this was closed "fixed" I would love to know what the fix was, version, details, example that actually works. There's no details.

So does that mean effectively iOS remote notifications are completely blocked/broken for MAUI? 

Does anyone have this actually working - now?

I've tried with Shiny, community toolkit, Plugin.Firebase, and others... no luck.

After struggling with this for a week now I am about to throw in the towel and hire a SWIFT developer instead.

**Comment by polieadie** [comment]
I solved mine by adding the firebase core initialization above LoadApplication.
Sample code is below:

`Firebase.Core.App.Configure();

LoadApplication(new App());

FirebasePushNotificationManager.Initialize(options, true);`

Hope this helps anyone.

**Comment by dgarcia2105** [comment]
hi Polieadie 
I tried but it didn't work

**Comment by dgarcia2105** [comment]
> I solved mine by adding the firebase core initialization above LoadApplication. Sample code is below:
> 
> `Firebase.Core.App.Configure();
> 
> LoadApplication(new App());
> 
> FirebasePushNotificationManager.Initialize(options, true);`
> 
> Hope this helps anyone.

ty for help but i have the same error

{System.NullReferenceException: Object reference not set to an instance of an object.
  at Plugin.FirebasePushNotification.FirebasePushNotificationManager.Initialize (Foundation.NSDictionary options, System.Boolean autoRegistration) [0x00029] in /Users/runner/work/1/s/Plugin.FirebasePushNotification/FirebasePushNotificationManager.ios.cs:141 
  at Admh.Clientes.Movil.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00013] in C:\Proyectos\admh\Admh.Clientes.Movil.iOS\AppDelegate.cs:69 
  at (wrapper managed-to-native) UIKit.UIApplication.xamarin_UIApplicationMain(int,intptr,intptr,intptr,intptr&)
  at UIKit.UIApplication.UIApplicationMain (System.Int32 argc, System.String[] argv, System.IntPtr principalClassName, System.IntPtr delegateClassName) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.6/src/Xamarin.iOS/UIKit/UIApplication.cs:58 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.6/src/Xamarin.iOS/UIKit/UIApplication.cs:84 
  at Admh.Clientes.Movil.iOS.Application.Main (System.String[] args) [0x00002] in C:\Proyectos\admh\Admh.Clientes.Movil.iOS\Main.cs:26 }

**Comment by dgarcia2105** [comment]
btw 
i am working in visual studio windows xamarin.ios

**Comment by dgarcia2105** [comment]
Help please someone!

**Comment by polieadie** [comment]
Please try below as well.

![image](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/assets/28383778/243bdc41-37cd-4f44-a421-bfbca55234e2)

**Comment by dgarcia2105** [comment]
> Please try below as well.
> 
> ![image](https://user-images.githubusercontent.com/28383778/247390091-243bdc41-37cd-4f44-a421-bfbca55234e2.png)

thanks for your prompt response,
I already tried but it didn't work

I am working from my windows laptop
remotely connected to my mac

I followed the tutorial:
https://www.youtube.com/watch?v=GNBuaAB8nR8&ab_channel=GeraldVersluis

I get the token, connected from the emulator, but when I try to test sending a notification from firebase messaging it never arrives,


I try to use my physical iPad but it returns the following error:

{System.NullReferenceException: Object reference not set to an instance of an object.
   at Plugin.FirebasePushNotification.FirebasePushNotificationManager.Initialize (Foundation.NSDictionary options, System.Boolean autoRegistration) [0x00029] in /Users/runner/work/1/s/Plugin.FirebasePushNotification/FirebasePushNotificationManager.ios.cs:141
   at Plugin.FirebasePushNotification.FirebasePushNotificationManager.Initialize (Foundation.NSDictionary options, Plugin.FirebasePushNotification.NotificationUserCategory[] notificationUserCategories, System.Boolean autoRegistration) [0x00000] in /Users/runner/work/1/s/Plugin.Fire basePushNotification/FirebasePushNotificationManager.ios .cs:176
   at Admh.Clientes.Movil.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00013] in C:\Proyectos\admh\Admh.Clientes.Movil.iOS\AppDelegate.cs:47
   at (wrapper managed-to-native) UIKit.UIApplication.xamarin_UIApplicationMain(int,intptr,intptr,intptr,intptr&)
   at UIKit.UIApplication.UIApplicationMain (System.Int32 argc, System.String[] argv, System.IntPtr principalClassName, System.IntPtr delegateClassName) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.6/ src/Xamarin.iOS/UIKit/UIApplication.cs:58
   at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00013] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.6/src/Xamarin.iOS /UIKit/UIApplication.cs:84
   at Admh.Customers.Mobile.iOS.Application.Main (System.String[] args) [0x00002] in C:\Projects\admh\Admh.Customers.Mobile.iOS\Main.cs:26 }

**Comment by dgarcia2105** [comment]
when i use postman it returns:

{
    "multicast_id": 4097073816387638982,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "NotRegistered"
        }
    ]
}

**Comment by carlosarizap** [comment]
Any fix? Same issue xamarin.ios on Windows VS Code 2022.

**Comment by rkotulan** [comment]
We ended up abandoning the use of this plugin and implemented FCM services directly. This plugin uses the old method to get the token. Now the notifications and GA4 work well for us again with the current versions of the google libraries.

**Comment by SliemBeji-FBC** [comment]
> We ended up abandoning the use of this plugin and implemented FCM services directly. This plugin uses the old method to get the token. Now the notifications and GA4 work well for us again with the current versions of the google libraries.

Can you please share your solution because i struggel with it myself for over 2 weeks now

**Comment by ysivivekanandv** [comment]
I also getting same error and app was crashing, 
here is the crashing error
 The type initializer for 'Plugin.FirebasePushNotifications.IFirebasePushNotification' threw an exception.
Plugin.FirebasePushNotifications
   at Plugin.FirebasePushNotifications.MauiAppBuilderExtensions.<>c.<UseFirebasePushNotifications>b__0_1(IServiceProvider c)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider provider)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at Yardi.Maui.SeniorResident.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) in C:\MAUIApps\SeniorResident\Platforms\iOS\AppDelegate.cs:line 22
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/2/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/2/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at Yardi.Maui.SeniorResident.Program.Main(String[] args) in C:\MAUIApps\SeniorResident\Platforms\iOS\Program.cs:line 13

After reading above I tried moving GoogleService-Info.plist from Platforms/iOS/Resources directly to project root folder and it sort out and start running :)
