### ISSUE TITLE
ANDROID: com.google.firebase.messaging.FirebaseMessagingService is inaccessible

### ISSUE THREAD

**Issue by rezamohamed** [CrossGeeks/FirebasePushNotificationPlugin#410]
After adding the Plugin (3.3.10 or 3.4.1), when debugging XF - Android I get the following error message

Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible

Exception:
java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.myco.myproject-6ueXHJpSOTg-VjPcM8KezQ==/base.apk!classes2.dex)
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3935)
	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

No such issues with XF - iOS.  I did have to manually upgrade the two following packages to the latest:

Xamarin.Firebase.iOS.CloudMessaging to 4.7.1
Xamarin.Firebase.iOS.InstanceID 4.8.0

Here are the other nuget packages that I have:

<img width="646" alt="Screen Shot 2022-02-06 at 5 56 14 PM" src="https://user-images.githubusercontent.com/18199852/152707569-81c92fac-68c4-45b7-abe7-602e0df7d235.png">

**Comment by rezamohamed** [comment]
I was able to bypass this issue by downgrading and explicitly installing nuget package Xamarin.Firebase.Iid version 71.1710.0
