### ISSUE TITLE
The "UnpackFrameworks" task failed unexpectedly. FirebaseMessaging already exists.

### ISSUE THREAD

**Issue by hercul1017** [CrossGeeks/FirebasePushNotificationPlugin#453]
## 🐛 Bug Report

After adding the plugin I get the following error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "UnpackFrameworks" task failed unexpectedly.
System.IO.IOException: The file 'obj\iPhone\Debug\device-builds\iphone9.4-15.4.1/Frameworks\FirebaseMessaging.framework\FirebaseMessaging' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName)
   at Xamarin.iOS.Tasks.Windows.Zip.CopyDirectory(String source, String destination) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Zip.cs:line 32
   at Xamarin.iOS.Tasks.Windows.Zip.Extract(String sourceFileName, String destinationPath) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Zip.cs:line 18
   at Xamarin.iOS.HotRestart.Tasks.UnpackFrameworks.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Tasks/UnpackHotRestartFrameworks.cs:line 55
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()			

The version is 3.4.35. Previous versions also had the same error for the IOS project. However Android project does not have the error and works fine.

**Platform:** 
- [x] :iphone: iOS

**Comment by WebcomCompany** [comment]
Search In google for change This file 'Xamarin.iOS.HotRestart.targets' your should be solved

**Comment by SliemBeji-FBC** [comment]
How to fix this problem without disabling the hot restart for
