### ISSUE TITLE
Failed to resolve Android.Gms.Tasks.Task Firebase.Messaging.FirebaseMessaging::DeleteToken()

### ISSUE THREAD

**Issue by sharunkumar** [CrossGeeks/FirebasePushNotificationPlugin#455]
Getting this error when building a Xamarin app on Azure Pipelines:

```
2023-01-16T04:32:47.9066034Z ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(648,5): Error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.FirebasePushNotification.FirebasePushNotificationManager::CleanUp(System.Boolean)' in assembly: 'Plugin.FirebasePushNotification.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Tasks.Task Firebase.Messaging.FirebaseMessaging::DeleteToken()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
```

Note: the project builds fine on my local machine though, not sure how to debug this 😥

### Configuration

**Version:** 3.4.35

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by sharunkumar** [comment]
So it turns out that `Xamarin.Firebase.Messaging` dependency was `71.1740.0` on the project. But this package required `122.0.0.5`. After upgrading it, it worked on Azure. Thought this was not a problem when running the build locally on my machine.
