### ISSUE TITLE
App Crashes at Initialization FirebasePushNotificationManager.Initialize(this, true); 

### ISSUE THREAD

**Issue by BhaurajBiradar001** [CrossGeeks/FirebasePushNotificationPlugin#456]
## 🐛 Bug Report
App Crashes at Initialization FirebasePushNotificationManager.Initialize(this, true); 

FirebasePushNotificationManager.Initialize(this, true); // Here app crashes

Default FirebaseApp is not initialized in this process com.firebase.sampleapp. Make sure to call FirebaseApp.initializeApp(Context) first.

// Stacktrace

{Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.firebase.sampleapp. Make sure to call FirebaseApp.initializeApp(Context) first.
at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <00c315a988634383b446eff646084784>:0
at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <00c315a988634383b446eff646084784>:0
at Firebase.Messaging.FirebaseMessaging.get_Instance () [0x00000] in C:\a_work\2\s\generated\com.google.firebase.firebase-messaging\obj\Release\monoandroid12.0\generated\src\Firebase.Messaging.FirebaseMessaging.cs:106
at Plugin.FirebasePushNotification.FirebasePushNotificationManager.Initialize (Android.Content.Context context, System.Boolean resetToken, System.Boolean createDefaultNotificationChannel, System.Boolean autoRegistration) [0x0002a] in /Users/runner/work/1/s/Plugin.FirebasePushNotification/FirebasePushNotificationManager.android.cs:123
at TotalConnect.Droid.MainApplication.OnCreate () [0x00032] in C:\Dev_Git\tc20e\TotalConnect\TotalConnect.Android\NotifApp.cs:37
--- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.firebase.sampleapp. Make sure to call FirebaseApp.initializeApp(Context) first.
at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
at com.google.firebase.messaging.FirebaseMessaging.getInstance(com.google.firebase:firebase-messaging@@22.0.0:1)
at crc6484fc9659366f968b.MainApplication.n_onCreate(Native Method)
at crc6484fc9659366f968b.MainApplication.onCreate(MainApplication.java:25)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7598)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2397)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8741)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
}
### Configuration

**Version:** 1.x

**Platform:** 
- [x ] :iphone: iOS
- [x] :robot: Android
- [x ] :checkered_flag: WPF
- [ x] :earth_americas: UWP
- [x ] :apple: MacOS
- [x ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by BhaurajBiradar001** [comment]
install the nuget GooglePlayServices.base
this worked for me..
